//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRH
    {
        public CRH()
        {
            this.CRH1 = new HashSet<CRH>();
            this.CRH_Opcion = new HashSet<CRH_Opcion>();
            this.Periodo_Extra = new HashSet<Periodo_Extra>();
            this.Periodo_Reportado = new HashSet<Periodo_Reportado>();
        }
    
        public int ID_CRH { get; set; }
        public Nullable<int> ID_CRH_Padre { get; set; }
        public Nullable<int> ID_Responsable { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Hoja { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<CRH> CRH1 { get; set; }
        public virtual CRH CRH2 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<CRH_Opcion> CRH_Opcion { get; set; }
        public virtual ICollection<Periodo_Extra> Periodo_Extra { get; set; }
        public virtual ICollection<Periodo_Reportado> Periodo_Reportado { get; set; }
    }
}
