//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRH_Opcion
    {
        public int ID_CRH_Opcion { get; set; }
        public Nullable<int> ID_Persona_CO { get; set; }
        public Nullable<int> ID_CRH_CO { get; set; }
    
        public virtual CRH CRH { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
