//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia_Reportado
    {
        public Dia_Reportado()
        {
            this.Periodo_Reportado = new HashSet<Periodo_Reportado>();
        }
    
        public int ID_Dia { get; set; }
        public Nullable<int> ID_Persona_DR { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Time_Zone_Dia { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Periodo_Reportado> Periodo_Reportado { get; set; }
    }
}
