//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONTIME_DBEntities : DbContext
    {
        public ONTIME_DBEntities()
            : base("name=ONTIME_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRH> CRH { get; set; }
        public virtual DbSet<CRH_Opcion> CRH_Opcion { get; set; }
        public virtual DbSet<Dia_Reportado> Dia_Reportado { get; set; }
        public virtual DbSet<Nivel_Compensacion> Nivel_Compensacion { get; set; }
        public virtual DbSet<Nivel_En_Fecha> Nivel_En_Fecha { get; set; }
        public virtual DbSet<Periodo_Extra> Periodo_Extra { get; set; }
        public virtual DbSet<Periodo_Reportado> Periodo_Reportado { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
