//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel_Compensacion
    {
        public Nivel_Compensacion()
        {
            this.Nivel_En_Fecha = new HashSet<Nivel_En_Fecha>();
        }
    
        public int ID_Nivel { get; set; }
        public string Nombre_Nivel { get; set; }
        public Nullable<decimal> Factor_De_Conversion { get; set; }
        public Nullable<decimal> Compensacion { get; set; }
    
        public virtual ICollection<Nivel_En_Fecha> Nivel_En_Fecha { get; set; }
    }
}
