//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo_Extra
    {
        public int ID_Periodo_Extra { get; set; }
        public Nullable<int> ID_Periodo_PE { get; set; }
        public Nullable<int> ID_CRH_PE { get; set; }
        public Nullable<int> Duracion { get; set; }
    
        public virtual CRH CRH { get; set; }
        public virtual Periodo_Reportado Periodo_Reportado { get; set; }
    }
}
