//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo_Reportado
    {
        public Periodo_Reportado()
        {
            this.Periodo_Extra = new HashSet<Periodo_Extra>();
        }
    
        public int ID_Periodo { get; set; }
        public Nullable<int> ID_Dia_PR { get; set; }
        public Nullable<int> ID_CRH_PR { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<System.DateTime> Timestamp_Autorizado { get; set; }
    
        public virtual CRH CRH { get; set; }
        public virtual Dia_Reportado Dia_Reportado { get; set; }
        public virtual ICollection<Periodo_Extra> Periodo_Extra { get; set; }
    }
}
