//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTimeDesktop.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.CRH = new HashSet<CRH>();
            this.CRH_Opcion = new HashSet<CRH_Opcion>();
            this.Dia_Reportado = new HashSet<Dia_Reportado>();
            this.Nivel_En_Fecha = new HashSet<Nivel_En_Fecha>();
            this.Persona1 = new HashSet<Persona>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID_Persona { get; set; }
        public Nullable<int> ID_Supervisor { get; set; }
        public string ID_Towa { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<CRH> CRH { get; set; }
        public virtual ICollection<CRH_Opcion> CRH_Opcion { get; set; }
        public virtual ICollection<Dia_Reportado> Dia_Reportado { get; set; }
        public virtual ICollection<Nivel_En_Fecha> Nivel_En_Fecha { get; set; }
        public virtual ICollection<Persona> Persona1 { get; set; }
        public virtual Persona Persona2 { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
